
# tap repositories and their packages

tap argon/mas
brew mas

## editor
cask 'google-chrome'


tap caskroom/cask

tap homebrew/core
brew git
brew chromedriver
brew wget
brew gmp
brew node
brew imagemagick
brew libmpc
brew mongodb
brew selenium-server-standalone
brew gcc@5

tap homebrew/versions

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 411246225 Caffeine (1.1.1)
appstore 408981434 iMovie (10.1.6)
appstore 409183694 Keynote (6.6.2)
appstore 539883307 LINE (5.3.0)
appstore 409203825 Numbers (3.6.2)
appstore 409201541 Pages (5.6.2)
appstore 405580712 StuffIt Expander (15.0.7)
appstore 425424353 The Unarchiver (3.11.3)
appstore 497799835 Xcode (8.2.1)
